# Container for building the Projecteur package
# Images available at: https://hub.docker.com/r/jahnf/projecteur/tags

FROM ubuntu:20.04

RUN apt-get update && mkdir /build
RUN apt-get install -y --no-install-recommends \
  ca-certificates \
  g++ \
  make \
  cmake \
  udev \
  git \
  pkg-config \
  qtdeclarative5-dev \
  qttools5-dev-tools \
  qt5-default \
  libqt5x11extras5-dev \
  libusb-1.0-0-dev

