# Container for building the Projecteur package
# Images available at: https://hub.docker.com/r/jahnf/projecteur/tags

FROM fedora:31

RUN dnf -y install --setopt=install_weak_deps=False --best \
  cmake \
  udev \
  gcc-c++ \
  tar \
  make \
  git \
  qt5-qtdeclarative-devel \
  pkg-config \
  rpm-build

RUN dnf -y install --setopt=install_weak_deps=False --best \
  qt5-linguist \
  qt5-qtx11extras-devel \
  libusbx-devel

