# Container for building the Projecteur package 

FROM ubuntu:19.04

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
  ca-certificates \
	g++ \
	make \
	cmake \
	git \
	pkg-config \
	qtdeclarative5-dev

RUN apt-get install -y --no-install-recommends udev
